-- Preserve editor-chosen dates on tentative events while leaving untouched
-- autogenerated projections tied to Job Info estimated_days.
ALTER TABLE calendar_events
  ADD COLUMN dates_manually_set INTEGER NOT NULL DEFAULT 0
  CHECK (dates_manually_set IN (0, 1));

-- Events without a calibration-cycle source were created manually.
UPDATE calendar_events
SET dates_manually_set = 1
WHERE source_calibration_date IS NULL;
