UPDATE job_info SET last_calibrated='2025-09-29' WHERE job_name='ALPCO';
UPDATE job_info SET last_calibrated='2025-03-19' WHERE job_name='AmberGen';
UPDATE job_info SET last_calibrated='2025-11-10' WHERE job_name='AMCO';
UPDATE job_info SET last_calibrated='2026-04-10' WHERE job_name='AmeriPath Irving';
UPDATE job_info SET last_calibrated='2025-11-21' WHERE job_name='AmeriPath Shelton & Dermpath Diagnostics';
UPDATE job_info SET last_calibrated='2026-03-12' WHERE job_name='Applied BioCode';
UPDATE job_info SET last_calibrated='2026-03-10' WHERE job_name='Asuragen';
UPDATE job_info SET last_calibrated='2025-10-23' WHERE job_name='Baptist Miami';
UPDATE job_info SET last_calibrated='2026-04-28' WHERE job_name='Baxter/Synovis';
UPDATE job_info SET last_calibrated='2026-04-28' WHERE job_name='Baxter/Synovis NY';
UPDATE job_info SET last_calibrated='2025-09-09' WHERE job_name='Baylor College of Medicine ';
UPDATE job_info SET last_calibrated='2026-03-10' WHERE job_name='BBAK';
UPDATE job_info SET last_calibrated='2026-06-24' WHERE job_name='BJC';
UPDATE job_info SET last_calibrated='2025-09-15' WHERE job_name='Black River Hospital';
UPDATE job_info SET last_calibrated='2026-07-01' WHERE job_name='Blood Center of New Orleans';
UPDATE job_info SET last_calibrated='2025-10-01' WHERE job_name='Boston Heart';
UPDATE job_info SET last_calibrated='2025-09-28' WHERE job_name='Boston Medical Center';
UPDATE job_info SET last_calibrated='2025-12-08' WHERE job_name='Broad Institute';
UPDATE job_info SET last_calibrated='2025-03-28' WHERE job_name='CA Dept of Public Health';
UPDATE job_info SET last_calibrated='2026-02-06' WHERE job_name='Case Western';
UPDATE job_info SET last_calibrated='2026-07-30' WHERE job_name='Cell Signaling';
UPDATE job_info SET last_calibrated='2026-01-29' WHERE job_name='Children''s Hospital of Atlanta';
UPDATE job_info SET last_calibrated='2025-10-30' WHERE job_name='Children''s Hospital of Boston';
UPDATE job_info SET last_calibrated='2025-08-13' WHERE job_name='Children''s Hospital San Diego';
UPDATE job_info SET last_calibrated='2026-02-19' WHERE job_name='Children''s National Phase 1';
UPDATE job_info SET last_calibrated='2025-11-20' WHERE job_name='Children''s National Phase 2';
UPDATE job_info SET last_calibrated='2026-02-12' WHERE job_name='CHLA';
UPDATE job_info SET last_calibrated='2026-04-30' WHERE job_name='City of San Antonio';
UPDATE job_info SET last_calibrated='2025-09-22' WHERE job_name='Cleveland DX';
UPDATE job_info SET last_calibrated='2026-03-12' WHERE job_name='Coastal Bend Blood Center';
UPDATE job_info SET last_calibrated='2026-03-26' WHERE job_name='Community Blood Center of Kansas City';
UPDATE job_info SET last_calibrated='2026-06-11' WHERE job_name='ConnectLife (Upstate NY Transplant)';
UPDATE job_info SET last_calibrated='2026-04-08' WHERE job_name='CPABB';
UPDATE job_info SET last_calibrated='2025-11-11' WHERE job_name='Cryo-Cell International';
UPDATE job_info SET last_calibrated='2026-02-13' WHERE job_name='CTS Dallas Bedford & St. Louis';
UPDATE job_info SET last_calibrated='2026-06-15' WHERE job_name='CTS East Coast';
UPDATE job_info SET last_calibrated='2026-03-03' WHERE job_name='CTS Phoenix';
UPDATE job_info SET last_calibrated='2025-12-03' WHERE job_name='Dallas Presbyterian';
UPDATE job_info SET last_calibrated='2026-06-29' WHERE job_name='DCN';
UPDATE job_info SET last_calibrated='2026-06-18' WHERE job_name='Delaware Public Health';
UPDATE job_info SET last_calibrated='2025-09-03' WHERE job_name='DiaSorin Molecular';
UPDATE job_info SET last_calibrated='2025-12-10' WHERE job_name='DNAZ';
UPDATE job_info SET last_calibrated='2025-10-10' WHERE job_name='Fralin Biomedical Research Institute';
UPDATE job_info SET last_calibrated='2026-04-29' WHERE job_name='Fred Hutchinson Cancer Research';
UPDATE job_info SET last_calibrated='2026-06-05' WHERE job_name='Gift of Life';
UPDATE job_info SET last_calibrated='2025-10-07' WHERE job_name='Harlem';
UPDATE job_info SET last_calibrated='2025-10-05' WHERE job_name='Heartland Blood Centers (Versiti)';
UPDATE job_info SET last_calibrated='2026-07-10' WHERE job_name='Helix';
UPDATE job_info SET last_calibrated='2026-04-16' WHERE job_name='HemaCare Northridge';
UPDATE job_info SET last_calibrated='2026-03-24' WHERE job_name='Hennepin Healthcare';
UPDATE job_info SET last_calibrated='2026-03-11' WHERE job_name='Hines VA Hospital';
UPDATE job_info SET last_calibrated='2026-07-29' WHERE job_name='Immucor Sirona';
UPDATE job_info SET last_calibrated='2025-09-03' WHERE job_name='Johns Hopkins Genomics';
UPDATE job_info SET last_calibrated='2026-01-08' WHERE job_name='Johns Hopkins Hospital';
UPDATE job_info SET last_calibrated='2025-11-12' WHERE job_name='Kaiser Berkley Marina';
UPDATE job_info SET last_calibrated='2026-07-28' WHERE job_name='Kentfield';
UPDATE job_info SET last_calibrated='2025-08-19' WHERE job_name='LabCorp (formerly MedTox Labs)';
UPDATE job_info SET last_calibrated='2026-08-04' WHERE job_name='LabCorp (formerly Physician Ref Lab)';
UPDATE job_info SET last_calibrated='2026-03-26' WHERE job_name='LAC Dept. of Public Health';
UPDATE job_info SET last_calibrated='2025-11-06' WHERE job_name='LAC USC (LA General)';
UPDATE job_info SET last_calibrated='2026-06-25' WHERE job_name='LifeServe BCI';
UPDATE job_info SET last_calibrated='2025-09-25' WHERE job_name='LifeSouth ';
UPDATE job_info SET last_calibrated='2025-09-24' WHERE job_name='Loyola';
UPDATE job_info SET last_calibrated='2026-06-24' WHERE job_name='MBC / Innovative Blood';
UPDATE job_info SET last_calibrated='2026-04-29' WHERE job_name='McAllen Medical Center';
UPDATE job_info SET last_calibrated='2026-03-31' WHERE job_name='Medic Regional Blood Center';
UPDATE job_info SET last_calibrated='2025-11-12' WHERE job_name='MedStar Medical Center ';
UPDATE job_info SET last_calibrated='2026-06-25' WHERE job_name='Memorial Jacksonville';
UPDATE job_info SET last_calibrated='2025-11-19' WHERE job_name='Mesoblast';
UPDATE job_info SET last_calibrated='2026-04-30' WHERE job_name='Methodist Health';
UPDATE job_info SET last_calibrated='2026-01-15' WHERE job_name='Miller Keystone';
UPDATE job_info SET last_calibrated='2026-04-02' WHERE job_name='Missouri Baptist';
UPDATE job_info SET last_calibrated='2025-07-02' WHERE job_name='Moab Regional Hospital';
UPDATE job_info SET last_calibrated='2025-08-28' WHERE job_name='Montefiore Nyack Hospital';
UPDATE job_info SET last_calibrated='2025-09-02' WHERE job_name='MORA (Mississippi Organ Recovery Agency)';
UPDATE job_info SET last_calibrated='2025-08-14' WHERE job_name='Mountain Point';
UPDATE job_info SET last_calibrated='2026-05-28' WHERE job_name='NBTC';
UPDATE job_info SET last_calibrated='2026-04-09' WHERE job_name='Nicklaus Children''s Hospital';
UPDATE job_info SET last_calibrated='2026-07-09' WHERE job_name='Northside Cherokee';
UPDATE job_info SET last_calibrated='2026-03-19' WHERE job_name='Northside Hospital Forsyth';
UPDATE job_info SET last_calibrated='2026-07-23' WHERE job_name='Northside, Atlanta, Duluth, Gwinett';
UPDATE job_info SET last_calibrated='2025-08-20' WHERE job_name='Northwestern Lake Forest Hospital';
UPDATE job_info SET last_calibrated='2025-11-06' WHERE job_name='Northwestern, Huntley, McHenry, Woodstock';
UPDATE job_info SET last_calibrated='2026-01-21' WHERE job_name='Novant ';
UPDATE job_info SET last_calibrated='2026-01-14' WHERE job_name='NYBC (New York Blood Center)';
UPDATE job_info SET last_calibrated='2026-04-23' WHERE job_name='Ohio State University Medical Center';
UPDATE job_info SET last_calibrated='2026-05-29' WHERE job_name='OneBlood Cypress';
UPDATE job_info SET last_calibrated='2026-06-05' WHERE job_name='OneBlood Orlando';
UPDATE job_info SET last_calibrated='2026-06-10' WHERE job_name='OneBlood St. Pete';
UPDATE job_info SET last_calibrated='2025-09-09' WHERE job_name='OneBlood TLH-PEN-CHAR-JAX';
UPDATE job_info SET last_calibrated='2025-07-16' WHERE job_name='OSS Health';
UPDATE job_info SET last_calibrated='2026-02-26' WHERE job_name='Our Lady of the Lake';
UPDATE job_info SET last_calibrated='2026-04-02' WHERE job_name='Pacific Diagonostic Laboratory';
UPDATE job_info SET last_calibrated='2023-11-17' WHERE job_name='Palm Beach Fertility';
UPDATE job_info SET last_calibrated='2026-03-25' WHERE job_name='Parkland';
UPDATE job_info SET last_calibrated='2026-05-04' WHERE job_name='Phase2 Labs';
UPDATE job_info SET last_calibrated='2026-05-29' WHERE job_name='Pinnacle';
UPDATE job_info SET last_calibrated='2026-06-25' WHERE job_name='Pomona College';
UPDATE job_info SET last_calibrated='2026-06-08' WHERE job_name='Priva Path Labs';
UPDATE job_info SET last_calibrated='2025-08-27' WHERE job_name='Queens';
UPDATE job_info SET last_calibrated='2026-07-14' WHERE job_name='Quest ACL';
UPDATE job_info SET last_calibrated='2026-06-18' WHERE job_name='Quest AmeriPath Memphis';
UPDATE job_info SET last_calibrated='2026-03-12' WHERE job_name='Quest Chantilly';
UPDATE job_info SET last_calibrated='2025-08-19' WHERE job_name='Quest Chicago';
UPDATE job_info SET last_calibrated='2025-12-18' WHERE job_name='Quest Clifton';
UPDATE job_info SET last_calibrated='2025-08-06' WHERE job_name='Quest Dallas';
UPDATE job_info SET last_calibrated='2026-06-30' WHERE job_name='Quest Houston';
UPDATE job_info SET last_calibrated='2026-02-26' WHERE job_name='Quest Las Vegas';
UPDATE job_info SET last_calibrated='2026-04-15' WHERE job_name='Quest Lenexa';
UPDATE job_info SET last_calibrated='2026-06-03' WHERE job_name='Quest Marlborough & Athena';
UPDATE job_info SET last_calibrated='2025-11-25' WHERE job_name='Quest Memphis';
UPDATE job_info SET last_calibrated='2026-06-30' WHERE job_name='Quest Miramar';
UPDATE job_info SET last_calibrated='2026-03-24' WHERE job_name='Quest Nichols Valencia Institute';
UPDATE job_info SET last_calibrated='2026-02-10' WHERE job_name='Quest OK';
UPDATE job_info SET last_calibrated='2026-03-26' WHERE job_name='Quest Pitts';
UPDATE job_info SET last_calibrated='2025-11-25' WHERE job_name='Quest Sacramento';
UPDATE job_info SET last_calibrated='2025-10-28' WHERE job_name='Quest Seattle';
UPDATE job_info SET last_calibrated='2026-02-27' WHERE job_name='Quest SJC Phase 1';
UPDATE job_info SET last_calibrated='2026-03-19' WHERE job_name='Quest SJC Phase 2';
UPDATE job_info SET last_calibrated='2025-08-05' WHERE job_name='Quest Tampa';
UPDATE job_info SET last_calibrated='2026-07-29' WHERE job_name='Quest Tucker';
UPDATE job_info SET last_calibrated='2026-05-28' WHERE job_name='Quest West Hills ';
UPDATE job_info SET last_calibrated='2026-01-29' WHERE job_name='Robert Wood Johnson';
UPDATE job_info SET last_calibrated='2026-04-07' WHERE job_name='Rooster Bio';
UPDATE job_info SET last_calibrated='2025-12-18' WHERE job_name='Roswell Park';
UPDATE job_info SET last_calibrated='2026-06-17' WHERE job_name='Santa Barbara Cottage Hospital';
UPDATE job_info SET last_calibrated='2025-09-30' WHERE job_name='SeQure DX';
UPDATE job_info SET last_calibrated='2025-11-19' WHERE job_name='Sharing Network';
UPDATE job_info SET last_calibrated='2025-10-09' WHERE job_name='Sibley Memorial';
UPDATE job_info SET last_calibrated='2025-09-14' WHERE job_name='Skyline DX';
UPDATE job_info SET last_calibrated='2026-01-21' WHERE job_name='South Dakota State Health';
UPDATE job_info SET last_calibrated='2026-06-10' WHERE job_name='St. Agnes';
UPDATE job_info SET last_calibrated='2026-02-26' WHERE job_name='St. Charles ';
UPDATE job_info SET last_calibrated='2026-02-02' WHERE job_name='St. Dominic Hospital';
UPDATE job_info SET last_calibrated='2025-11-20' WHERE job_name='St. Johns Hospital';
UPDATE job_info SET last_calibrated='2025-09-03' WHERE job_name='St. Judes';
UPDATE job_info SET last_calibrated='2026-05-27' WHERE job_name='St. Mary Good Samaritan';
UPDATE job_info SET last_calibrated='2026-01-08' WHERE job_name='Stanford Blood Center';
UPDATE job_info SET last_calibrated='2026-06-02' WHERE job_name='SunCoast Blood Centers';
UPDATE job_info SET last_calibrated='2026-02-24' WHERE job_name='Texas Heart Institute at St. Lukes';
UPDATE job_info SET last_calibrated='2026-07-25' WHERE job_name='The Blood Connection';
UPDATE job_info SET last_calibrated='2026-07-07' WHERE job_name='Trio US';
UPDATE job_info SET last_calibrated='2025-11-25' WHERE job_name='True Care';
UPDATE job_info SET last_calibrated='2025-10-10' WHERE job_name='UCI';
UPDATE job_info SET last_calibrated='2026-06-10' WHERE job_name='UCLA (CHS Laboratories)';
UPDATE job_info SET last_calibrated='2026-07-01' WHERE job_name='UCLA Brentwood SID 432';
UPDATE job_info SET last_calibrated='2026-05-28' WHERE job_name='UCLA Community Clinics';
UPDATE job_info SET last_calibrated='2026-04-20' WHERE job_name='UCLA Cousins Center for Psychoneuroimmunology';
UPDATE job_info SET last_calibrated='2026-06-05' WHERE job_name='UCLA Factor Building';
UPDATE job_info SET last_calibrated='2026-05-07' WHERE job_name='UCLA Health Labs & SMH';
UPDATE job_info SET last_calibrated='2026-01-22' WHERE job_name='UCLA Healthcare Labs';
UPDATE job_info SET last_calibrated='2026-05-28' WHERE job_name='UCLA HGCTF GMP';
UPDATE job_info SET last_calibrated='2026-03-13' WHERE job_name='UCLA Immunogenetics - OAL SID 433';
UPDATE job_info SET last_calibrated='2026-04-01' WHERE job_name='UCLA Med Ctr NEW';
UPDATE job_info SET last_calibrated='2026-06-05' WHERE job_name='UCLA Medical Center SID 430';
UPDATE job_info SET last_calibrated='2026-03-30' WHERE job_name='UCLA Medical Center SID 431';
UPDATE job_info SET last_calibrated='2026-05-07' WHERE job_name='UCLA Oncology Clinics (Hematology)';
UPDATE job_info SET last_calibrated='2025-12-11' WHERE job_name='UCLA Ronald Reagan Hospital';
UPDATE job_info SET last_calibrated='2026-05-26' WHERE job_name='UCLA Student Health';
UPDATE job_info SET last_calibrated='2026-07-09' WHERE job_name='UCLA Wasserman Building';
UPDATE job_info SET last_calibrated='2026-04-16' WHERE job_name='UCLA West Valley & Mid-Wilshire';
UPDATE job_info SET last_calibrated='2026-05-20' WHERE job_name='UHHS Phase 1';
UPDATE job_info SET last_calibrated='2026-05-20' WHERE job_name='UHHS Phase 2';
UPDATE job_info SET last_calibrated='2026-02-05' WHERE job_name='University of Mississippi (UMMC)';
UPDATE job_info SET last_calibrated='2026-02-11' WHERE job_name='UT Health Tyler';
UPDATE job_info SET last_calibrated='2026-04-29' WHERE job_name='UTHSC - San Antonio';
UPDATE job_info SET last_calibrated='2026-03-06' WHERE job_name='VA Greater Los Angeles Healthcare System';
UPDATE job_info SET last_calibrated='2026-04-03' WHERE job_name='VA Miami';
UPDATE job_info SET last_calibrated='2026-05-06' WHERE job_name='VA Milwaukee';
UPDATE job_info SET last_calibrated='2026-04-07' WHERE job_name='VA New Mexico';
UPDATE job_info SET last_calibrated='2026-06-03' WHERE job_name='Virginia Hospital Center';
UPDATE job_info SET last_calibrated='2026-08-04' WHERE job_name='Werfen (BioArray)';
UPDATE job_info SET last_calibrated='2026-02-18' WHERE job_name='Werfen Waukesha';
UPDATE job_info SET last_calibrated='2025-11-20' WHERE job_name='Zeus';
