CREATE TABLE IF NOT EXISTS job_info (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  customer      TEXT NOT NULL UNIQUE,
  job_name      TEXT,
  servers       TEXT,
  sensors       INTEGER,
  num_tech      INTEGER,
  estimated_days INTEGER,
  site_address  TEXT,
  offsites      TEXT,
  comments      TEXT,
  vpn_works     TEXT,
  airport_info  TEXT,
  emerald_aisle TEXT,
  prev_hotel    TEXT,
  hotel_comments TEXT,
  main_contact  TEXT,
  other_contacts TEXT,
  contact_notes TEXT,
  credentials   TEXT,
  primary_tech  TEXT,
  meters        TEXT,
  o2            INTEGER,
  server_version   TEXT,
  hardware      TEXT,
  report        TEXT,  
  restaurants   TEXT,
  other_notes   TEXT,
  active        INTEGER DEFAULT 1,
  last_calibrated TEXT,
  updated_at    TEXT DEFAULT (datetime('now'))
);
