import {
  addBusinessDays,
  addDays,
  addMonths,
  addYears,
  differenceInCalendarDays,
  format,
  isValid,
  parseISO,
} from 'date-fns';
import { CONFIG } from '../config.js';

const CONFLICT_WINDOW_DAYS = 90;

function mondayOnOrBefore(date) {
  let monday = new Date(date);
  while (monday.getDay() !== 1) monday = addDays(monday, -1);
  return monday;
}

function nextBusinessDay(date) {
  let next = addDays(date, 1);
  while (next.getDay() === 0 || next.getDay() === 6) next = addDays(next, 1);
  return next;
}

function businessDates(start, duration) {
  return Array.from({ length: duration }, (_, index) =>
    format(addBusinessDays(start, index), 'yyyy-MM-dd')
  );
}

function estimatedDays(job) {
  return Math.max(1, Math.ceil(Number(job?.estimated_days) || 1));
}

function normalizedName(value) {
  return String(value || '').trim().toLowerCase();
}

export function isAutogeneratedTentativeNote(value) {
  const note = String(value || '').trim();
  return /^Auto set as tentative\s+(?:\u2014|-)\s+six-month rollover from last calibration:\s*\d{4}-\d{2}-\d{2}$/i.test(note)
    || /^Tentative\s+(?:\u2014|-)\s+based on [A-Z]{3} \d{4} calibration$/i.test(note)
    || /^Tentative\s+(?:\u2014|-)\s+six-month rollover from \d{4}-\d{2}-\d{2}$/i.test(note);
}

export function autogeneratedTentativeNote(lastCalibrated) {
  return `Auto set as tentative \u2014 six-month rollover from last calibration: ${lastCalibrated}`;
}

export function notesForStatus(notes, status) {
  return normalizedName(status) !== 'tentative' && isAutogeneratedTentativeNote(notes)
    ? null
    : notes;
}

function jobsByName(jobInfoMap) {
  return new Map(
    Object.values(jobInfoMap || {})
      .filter(job => job?.job_name)
      .map(job => [normalizedName(job.job_name), job])
  );
}

function jobsById(jobInfoMap) {
  return new Map(
    Object.values(jobInfoMap || {})
      .filter(job => job?.id !== null && job?.id !== undefined)
      .map(job => [String(job.id), job])
  );
}

export function historicalAssignmentNames(job, events = [], assignments = []) {
  const lastCalibrated = parseISO(String(job?.last_calibrated || ''));
  if (!isValid(lastCalibrated)) return [];

  const historicalEvent = (events || [])
    .filter(event => {
      if (event?.isGhost || normalizedName(event?.status) === 'tentative') return false;
      if (normalizedName(event?.event_type) !== 'calibration') return false;
      const matchesJob = String(event?.job_info_id || '') === String(job?.id || '')
        || normalizedName(event?.title) === normalizedName(job?.job_name);
      const eventDate = parseISO(String(event?.end_date || event?.start_date || ''));
      return matchesJob && isValid(eventDate)
        && Math.abs(differenceInCalendarDays(eventDate, lastCalibrated)) < CONFLICT_WINDOW_DAYS;
    })
    .sort((a, b) => {
      const aDate = parseISO(String(a.end_date || a.start_date));
      const bDate = parseISO(String(b.end_date || b.start_date));
      return Math.abs(differenceInCalendarDays(aDate, lastCalibrated))
        - Math.abs(differenceInCalendarDays(bDate, lastCalibrated));
    })[0];

  if (!historicalEvent) return [];
  return [...new Set((assignments || [])
    .filter(assignment => String(assignment.event_id) === String(historicalEvent.id))
    .map(assignment => CONFIG.TECHNICIANS.find(
      technician => technician.toLowerCase() === String(assignment.tech_name || '').trim().toLowerCase()
    ))
    .filter(Boolean))];
}

export function assignmentNames(job, historicalNames = []) {
  const primary = String(job.primary_tech || '').trim();
  const canonicalPrimary = CONFIG.TECHNICIANS.find(
    technician => technician.toLowerCase() === primary.toLowerCase()
  );
  if (Number(job.num_tech) === 1 && canonicalPrimary) return [canonicalPrimary];

  const historicalTeam = [...new Set(historicalNames)].filter(name =>
    CONFIG.TECHNICIANS.includes(name)
  );
  const expectedTeamSize = Number(job.num_tech) || 0;
  if (historicalTeam.length && (!expectedTeamSize || historicalTeam.length === expectedTeamSize)) {
    return historicalTeam;
  }
  return [CONFIG.UNASSIGNED_TECHNICIAN];
}

function activeJob(job) {
  return job.active === null || job.active === undefined || job.active === '' || Number(job.active) === 1;
}

function addBusyDate(busyByTech, techName, date) {
  if (!busyByTech.has(techName)) busyByTech.set(techName, new Set());
  busyByTech.get(techName).add(date);
}

function reserveDates(busyByTech, techNames, dates) {
  techNames.forEach(techName => dates.forEach(date => addBusyDate(busyByTech, techName, date)));
}

function firstAvailableSlot(targetStart, duration, techNames, busyByTech) {
  let start = targetStart;
  while (true) {
    const dates = businessDates(start, duration);
    const occupied = techNames.some(techName =>
      dates.some(date => busyByTech.get(techName)?.has(date))
    );
    if (!occupied) return { start, dates };
    start = nextBusinessDay(start);
  }
}

export function normalizeTentativeCalendar(events, assignments, jobInfoMap, techEvents = []) {
  const jobLookup = jobsByName(jobInfoMap);
  const jobIdLookup = jobsById(jobInfoMap);
  const tentativeIds = new Set();
  const normalizedEvents = (events || []).map(event => {
    const isAutomaticTentative = !event.isGhost
      && normalizedName(event.status) === 'tentative'
      && Boolean(event.source_calibration_date)
      && Number(event.dates_manually_set || 0) !== 1;
    if (!isAutomaticTentative) return event;
    const job = jobIdLookup.get(String(event.job_info_id))
      || jobLookup.get(normalizedName(event.title));
    const start = parseISO(String(event.start_date || ''));
    if (!job || !isValid(start)) return event;

    tentativeIds.add(String(event.id));
    const dates = businessDates(start, estimatedDays(job));
    return { ...event, end_date: dates[dates.length - 1] };
  });

  const assignmentsByEvent = new Map();
  (assignments || []).forEach(assignment => {
    const id = String(assignment.event_id);
    if (!assignmentsByEvent.has(id)) assignmentsByEvent.set(id, []);
    assignmentsByEvent.get(id).push(assignment);
  });

  const untouchedAssignments = (assignments || []).filter(
    assignment => !tentativeIds.has(String(assignment.event_id))
  );
  const normalizedTentativeAssignments = normalizedEvents.flatMap(event => {
    const id = String(event.id);
    if (!tentativeIds.has(id)) return [];
    const job = jobIdLookup.get(String(event.job_info_id))
      || jobLookup.get(normalizedName(event.title));
    const existing = assignmentsByEvent.get(id) || [];
    const techNames = [...new Set(existing.map(a => a.tech_name).filter(Boolean))];
    const dates = businessDates(parseISO(event.start_date), estimatedDays(job));
    const historicalNames = historicalAssignmentNames(job, events, assignments);
    const proposedTechs = assignmentNames(job, historicalNames);
    const otherAssignments = (assignments || []).filter(a => String(a.event_id) !== id);
    const proposedBusy = new Set([
      ...otherAssignments.map(a => `${a.tech_name}\u0000${a.date}`),
      ...(techEvents || []).map(a => `${a.tech_name}\u0000${a.date}`),
    ]);
    const allAvailable = proposedTechs.every(techName =>
      techName === CONFIG.UNASSIGNED_TECHNICIAN
      || dates.every(date => !proposedBusy.has(`${techName}\u0000${date}`))
    );
    const assignedTechs = techNames.length
      ? techNames
      : allAvailable ? proposedTechs : [CONFIG.UNASSIGNED_TECHNICIAN];
    return assignedTechs.flatMap(techName =>
      dates.map(date => ({ event_id: event.id, tech_name: techName, date }))
    );
  });

  return {
    events: normalizedEvents,
    assignments: [...untouchedAssignments, ...normalizedTentativeAssignments],
  };
}

export function generateTentativeJobs(
  jobInfoMap,
  realEvents,
  now = new Date(),
  realAssignments = [],
  techEvents = []
) {
  const jobs = Object.values(jobInfoMap || {});
  const busyByTech = new Map();

  (realAssignments || []).forEach(assignment => {
    if (assignment?.tech_name && assignment?.date) {
      addBusyDate(busyByTech, assignment.tech_name, assignment.date);
    }
  });
  (techEvents || []).forEach(event => {
    if (event?.tech_name && event?.date) addBusyDate(busyByTech, event.tech_name, event.date);
  });

  const candidates = jobs.flatMap(job => {
    if (!job?.job_name || !activeJob(job) || !job.last_calibrated) return [];

    const lastCalibrated = parseISO(String(job.last_calibrated));
    if (!isValid(lastCalibrated) || now < addMonths(lastCalibrated, 6)) return [];

    const anniversary = addYears(lastCalibrated, 1);
    const targetStart = mondayOnOrBefore(anniversary);
    const hasConflict = (realEvents || []).some(event =>
      !event.isGhost &&
      (String(event.job_info_id || '') === String(job.id || '')
        || normalizedName(event.title) === normalizedName(job.job_name)) &&
      isValid(parseISO(String(event.start_date || ''))) &&
      Math.abs(differenceInCalendarDays(parseISO(event.start_date), targetStart)) < CONFLICT_WINDOW_DAYS
    );
    if (hasConflict) return [];

    return [{ job, lastCalibrated, targetStart }];
  }).sort((a, b) =>
    a.targetStart - b.targetStart || String(a.job.job_name).localeCompare(String(b.job.job_name))
  );

  return candidates.map(({ job, targetStart }) => {
    const duration = estimatedDays(job);
    const historicalNames = historicalAssignmentNames(job, realEvents, realAssignments);
    const techNames = assignmentNames(job, historicalNames);
    const slot = firstAvailableSlot(targetStart, duration, techNames, busyByTech);
    reserveDates(busyByTech, techNames, slot.dates);

    const ghostId = `ghost-job-${job.id ?? job.job_name}`;
    const ghostAssignments = techNames.flatMap(techName =>
      slot.dates.map(date => ({ tech_name: techName, date, event_id: ghostId }))
    );

    return {
      id: ghostId,
      job_info_id: job.id ?? null,
      source_calibration_date: job.last_calibrated,
      title: job.job_name,
      event_type: 'calibration',
      status: 'tentative',
      customer: job.customer ?? null,
      start_date: slot.dates[0],
      end_date: slot.dates[slot.dates.length - 1],
      ticket_id: null,
      notes: autogeneratedTentativeNote(job.last_calibrated),
      isGhost: true,
      sourceJobInfo: job,
      ghostAssignments,
    };
  });
}

export function materializeTentativeJob(eventData) {
  const realData = { ...eventData, id: undefined };
  delete realData.isGhost;
  delete realData.sourceJobInfo;
  delete realData.ghostAssignments;
  return realData;
}
