/** Defines calendar API settings, technicians, event types, and semantic color mappings. */
export const CONFIG = {
  WORKER_URL: 'https://flat-tree-380f.leightonsolo.workers.dev',
  API_KEY: 'U87iy7VynFYLJUDnfUYBJHnRKbRiQO3Z',
  EDITOR_TOKEN_KEY: 'cal_editor_token',
  TECHNICIANS: [
    'Daniel',
    'Dejan',
    'Leighton',
    'Joey',
    'Brendon',
    'Matt',
    'Fernando',
    'Bissen',
  ],
  UNASSIGNED_TECHNICIAN: 'Unassigned',
  EVENT_TYPES: ['calibration', 'install', 'upgrade', 'mapping', 'other'],
  EVENT_STATUSES: ['tentative', 'ticketed', 'confirmed', 'booked'],
  TECH_EVENT_TYPES: ['pto', 'holiday', 'office', 'jury_duty', 'Software', 'other'],
  STATUS_COLORS: {
    tentative: { bg: 'var(--event-tentative-bg)', fg: 'var(--event-tentative-text)', border: 'var(--event-tentative-border)' },
    ticketed:  { bg: 'var(--event-ticketed-bg)', fg: 'var(--event-ticketed-text)', border: 'var(--event-ticketed-border)' },
    confirmed: { bg: 'var(--event-confirmed-bg)', fg: 'var(--event-confirmed-text)', border: 'var(--event-confirmed-border)' },
    booked:    { bg: 'var(--event-booked-bg)', fg: 'var(--event-booked-text)', border: 'var(--event-booked-border)' },
  },
  TYPE_COLORS: {
    calibration: null,       // uses status color
    install:     { bg: 'var(--event-install-bg)', fg: 'var(--event-install-text)', border: 'var(--event-install-border)' },
    upgrade:     { bg: 'var(--event-upgrade-bg)', fg: 'var(--event-upgrade-text)', border: 'var(--event-upgrade-border)' },
    mapping:     { bg: 'var(--event-mapping-bg)', fg: 'var(--event-mapping-text)', border: 'var(--event-mapping-border)' },
    other:       { bg: 'var(--event-other-bg)', fg: 'var(--event-other-text)', border: 'var(--event-other-border)' },
    pto:         { bg: 'var(--event-pto-bg)', fg: 'var(--event-pto-text)', border: 'var(--event-pto-border)' },
    holiday:     { bg: 'var(--event-holiday-bg)', fg: 'var(--event-holiday-text)', border: 'var(--event-holiday-border)' },
    jury_duty:   { bg: 'var(--event-jury-bg)', fg: 'var(--event-jury-text)', border: 'var(--event-jury-border)' },
    office:      { bg: 'var(--event-office-bg)', fg: 'var(--event-office-text)', border: 'var(--event-office-border)' },
  },
  TECH_COLORS: {
  'Leighton': { bg: 'var(--tech-leighton-bg)', fg: 'var(--tech-leighton-text)', border: 'var(--tech-leighton-border)' },
  'Fernando': { bg: 'var(--tech-fernando-bg)', fg: 'var(--tech-fernando-text)', border: 'var(--tech-fernando-border)' },
  'Daniel':   { bg: 'var(--tech-daniel-bg)', fg: 'var(--tech-daniel-text)', border: 'var(--tech-daniel-border)' },
  'Joey':     { bg: 'var(--tech-joey-bg)', fg: 'var(--tech-joey-text)', border: 'var(--tech-joey-border)' },
  'Bissen':   { bg: 'var(--tech-bissen-bg)', fg: 'var(--tech-bissen-text)', border: 'var(--tech-bissen-border)' },
  'Dejan':    { bg: 'var(--tech-dejan-bg)', fg: 'var(--tech-dejan-text)', border: 'var(--tech-dejan-border)' },
  'Brendon':     { bg: 'var(--tech-brendon-bg)', fg: 'var(--tech-brendon-text)', border: 'var(--tech-brendon-border)' },
  'Matt':     { bg: 'var(--tech-matt-bg)', fg: 'var(--tech-matt-text)', border: 'var(--tech-matt-border)' },
  'Unassigned': { bg: 'var(--tech-unassigned-bg)', fg: 'var(--tech-unassigned-text)', border: 'var(--tech-unassigned-border)' },
  },
};
